osx_image: xcode8.2
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
    env: APP_BIN_OUTPUT=serial-port-darwin-x64
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1 APP_BIN_OUTPUT=serial-port-linux-x64
    compiler: clang
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
- chmod +x scripts/build.sh
install:
- nvm install 6
- npm install
script:
- scripts/build.sh

after_success:
- npm run coveralls

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "release-builds/$APP_BIN_OUTPUT/$APP_BIN_OUTPUT.zip"
  skip_cleanup: true
  on:
    tags: true
    branch: master