os: Visual Studio 2015

environment:
  nodejs_version: "6"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test: off
deploy: off

build: on

build_script:
  - npm run package-win32
